spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:testdb"
    username: sa
    password: password
    database-platform: org.hibernate.dialect.H2Dialect
    compose:
      enabled: false

jwt:
  expiration: 10_000 # 10 seconds