# DATABASE CONFIGURATION
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}


server:
  port: 80
