spring:
  config:
    import: optional:file:.env.local[.properties]

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/khutir_craft
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true

  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

cloudinary:
  cloud_name: ci-test-cloud
  api_key: test_api_key
  api_secret: test_api_secret

jwt:
  secret: ${JWT_SECRET:dummy-secret-phrase}
  session-timeout: ${JWT_SESSION_TIMEOUT:600000}

logging:
  level:
    root: INFO
    com.khutircraftubackend: DEBUG
  file:
    name: logs/latest.log

storage:
  local:
    base-path: ${LOCAL_STORAGE_BASEPATH:./uploads}