version: '3.6'

volumes:
  pg_marketplace:

services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - pg_marketplace:/var/lib/postgresql/data
  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - ../.env
