name: "khutir-craft"
services:
  app:
    container_name: "khutir-app"
    depends_on:
      - db
    environment:
      # this needs to be overridden to work inside the docker network:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/khutir_craft"
    ports:
      - "8080:8080"
    env_file:
      - ../.env
      - ../.env.local
    build:
      context: ../
      dockerfile: docker/Dockerfile

  db:
    container_name: "khutir-db"
    image: postgres:16.4-alpine3.20
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - khutir-db-data:/var/lib/postgresql/data
      - ./dbsetup.sql:/docker-entrypoint-initdb.d/dbsetup.sql

  mail:
    container_name: "khutir-mail"
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  khutir-db-data:
    name: "khutir-db-data"
    labels:
      - "com.khutir-craft.db"
