services:
  app:
    container_name: food-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/khutir_craftu"
    ports:
      - "8081:8080"
    env_file:
      - ../.env.local
    build:
      context: ../
      dockerfile: docker/Dockerfile

  db:
    container_name: food-database
    image: postgres:16.4-alpine3.20
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_marketplace:/var/lib/postgresql/data
      - ../src/main/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  pg_marketplace:
