CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email VARCHAR(40) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    enabled BOOLEAN DEFAULT FALSE,
    confirmed BOOLEAN,
    creation_date TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX idx_email ON users (email);